import glob, sys

Import('env')

env = env.Copy()
env.Append(CPPPATH = ['#/engine/core'])
env.Append(LIBPATH = ['#/engine/core'])

env.Append(LIBS = ['libfife','libUnitTest++'])

if sys.platform == 'darwin':
	env.Append(LIBPATH = ['/System/Library'])
	env.Append(LINKFLAGS='-framework SDL')
	env.Append(LINKFLAGS='-framework SDL_image')
	env.Append(LINKFLAGS='-framework SDL_ttf')
        env.Append(LINKFLAGS=['-Wl'])
else:
        env.Append(LINKFLAGS=['-Wl,-rpath,../../ext/install/lib,-rpath,../../engine'])

# The test_fife.py script relies on this specific layout.
# Check it, if you change something here
env.Program('testprog_rect', ['test_rect.cpp'])
env.Program('testprog_dat1', ['test_dat1.cpp'])
env.Program('testprog_dat2', ['test_dat2.cpp'])
env.Program('testprog_gui', ['test_gui.cpp'])
env.Program('testprog_images', ['test_images.cpp'])
env.Program('testprog_imagepool', ['test_imagepool.cpp'])
env.Program('testprog_vfs', ['test_vfs.cpp'])


if env['zip']:
	env.Program('testprog_zip', ['test_zip.cpp'])

# vim: set filetype=python :
