import glob

Import('env')

env = env.Copy()
env.Append(CPPPATH = ['#/engine/core'])
env.Append(LIBPATH = ['#/engine/core'])
env.Append(LIBPATH = ['/System/Library'])
env.Append(LINKFLAGS='-framework SDL')
env.Append(LINKFLAGS='-framework SDL_image')
env.Append(LINKFLAGS='-framework SDL_ttf')

env.Append(LIBS = ['libfife','boost_unit_test_framework'])
env.Append(LINKFLAGS=['-Wl'])

# The test_all.py script relies on this specific layout.
# Check it, if you change something here
env.Program('testprog_rect', ['test_rect.cpp'])
env.Program('testprog_dat1', ['test_dat1.cpp'])
env.Program('testprog_dat2', ['test_dat2.cpp'])
env.Program('testprog_gui', ['test_gui.cpp'])
env.Program('testprog_images', ['test_images.cpp'])
env.Program('testprog_animations', ['test_animations.cpp'])
env.Program('testprog_imagepool', ['test_imagepool.cpp'])

# vim: set filetype=python :
