import glob

Import('env')

env = env.Copy()
env.Append(CPPPATH = ['#/engine/core'])
env.Append(LIBPATH = ['#/engine/core'])
env.Append(LIBS = ['libfife','boost_unit_test_framework'])
env.Append(LINKFLAGS=['-Wl,-rpath,../../ext/install/lib,-rpath,../../engine'])

# The test_all.py script relies on this specific layout.
# Check it, if you change something here
env.Program('testprog_rect', ['test_rect.cpp'])
env.Program('testprog_dat1', ['test_dat1.cpp'])
env.Program('testprog_dat2', ['test_dat2.cpp'])

# vim: set filetype=python :
