import glob
import os

Import('env')

subproject_files = []

env.Append(CPPPATH = ['#src'])

files = glob.glob('*.cpp') + subproject_files

interfaces = glob.glob('*.ui')

[env.Uic4(uic)
	for uic in interfaces]

env.Program('fifedit', files)

# vim: set filetype=python :
