Import('env')

sconscripts = []
if env['lite'] == 0:
	sconscripts  += [
		'engine/SConscript',
		'guimap_test/SConscript',
	]

if env['lite'] == 1:
	sconscripts = [
		'engine/SConscript'
	]

SConscript(sconscripts)
# vim: set filetype=python :
