// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2005 - 2026 Fifengine contributors
// AUTOGENERATED FILE, DO NOT EDIT

#ifndef FIFE_VERSION_HPP
#define FIFE_VERSION_HPP

#include <string>
#include <string_view>

/**
 * CMake replacement tokens used by configure_file(@ONLY):
 *
 * FIFE_NAME
 * FIFE_DESC
 * FIFE_HOMEPAGE
 * FIFE_LICENSE
 * PROJECT_VERSION_MAJOR
 * PROJECT_VERSION_MINOR
 * PROJECT_VERSION_PATCH
 * CURRENT_YEAR
 */

namespace FIFE
{

    struct semantic_version
    {
            int major = 0;
            int minor = 5;
            int patch = 0;
    };

    class app_version
    {
        public:
            // clang-format off
        static constexpr std::string_view name        = "fifengine";
        static constexpr std::string_view version     = "0.5.0";
        static constexpr std::string_view license     = "LGPL-2.1";
        static constexpr std::string_view description = "Fifengine is a multi-platform isometric game engine written in C++.";
        static constexpr std::string_view homepage    = "https://github.com/fifengine/fifengine";
        static constexpr std::string_view copyright   = "Copyright (c) Fifengine contributors, 2005-2026.";
        static constexpr semantic_version semver{
            .major = 0,
            .minor = 5,
            .patch = 0,
        };
        static constexpr int version_id = (0 * 10000) + (5 * 100) + 0;
            // clang-format on

            /**
             * Getters - c_str() types
             */

            static constexpr char const * get_name()
            {
                return name.data();
            }

            static constexpr char const * get_version()
            {
                return version.data();
            }

            static constexpr char const * get_license()
            {
                return license.data();
            }

            static constexpr char const * get_description()
            {
                return description.data();
            }

            static constexpr char const * get_homepage()
            {
                return homepage.data();
            }

            static constexpr char const * get_copyright()
            {
                return copyright.data();
            }

            static constexpr int get_major()
            {
                return semver.major;
            }

            static constexpr int get_minor()
            {
                return semver.minor;
            }

            static constexpr int get_patch()
            {
                return semver.patch;
            }

            static constexpr int get_version_id()
            {
                return version_id;
            }
    };

} // namespace FIFE

#endif // FIFE_VERSION_HPP
