Import('env')

FILESLIST = [ 'util/image_provider.cpp', 'util/frm_provider.cpp' ]

XML_LIST = ['xmlmap/imagetool.cpp', 'xmlmap/mapreader.cpp']

objlist = []

for file in FILESLIST:
	objlist += env.Object(file)

if env['xmlmap'] == 1:
	for file in XML_LIST:
		objlist += env.Object(file)


objlist += SConscript('fallout/SConscript')

Return('objlist')

# vim: set filetype=python :
