Import('env')

FILESLIST = [ 'tinystr.cpp', 'tinyxml.cpp', 'tinyxmlerror.cpp',
       'tinyxmlerror.cpp', 'tinyxmlparser.cpp' ]

objlist = []

if env['tinyxml'] == 1:
	for file in FILESLIST:
		objlist += env.Object(file)

Return('objlist')
