import glob

Import('env')

env = env.Copy()
env.Append(CPPPATH = ['#src/engine'])
env.Append(LIBS = ['fife','boost_unit_test_framework'])
env.Append(LIBPATH = ['#src/engine'])

env.Program('test_geometry', ['test_geometry.cpp'])
env.Program('test_rect', ['test_rect.cpp'])
env.Program('test_events', ['test_events.cpp'])

# vim: set filetype=python :
