from typing import Any

class _Dynamic:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class ActionListener(_Dynamic): ...
class MouseListener(_Dynamic): ...
class KeyListener(_Dynamic): ...
class WidgetListener(_Dynamic): ...
class Widget(_Dynamic): ...
class GuiFont(_Dynamic): ...
class GuiImage(_Dynamic): ...

Color: Any

class Point(_Dynamic):
    x: int
    y: int

class Size(_Dynamic): ...
class ListModel(_Dynamic): ...
class FcnPointVector(list[Point]): ...

class Container(Widget):
    Vertical: int
    Horizontal: int
    Circular: int
    AutoSize: int
    Absolute: int

class ScrollArea(Container):
    ShowAuto: int
    ShowNever: int
    ShowAlways: int
    SHOW_AUTO: int
    SHOW_NEVER: int
    SHOW_ALWAYS: int

class Slider(Widget):
    Horizontal: int
    Vertical: int

class PercentageBar(Widget):
    HORIZONTAL: int
    VERTICAL: int

class ResizableWindow(Widget):
    CURSOR_DIRECTION_L: int
    CURSOR_DIRECTION_R: int
    CURSOR_DIRECTION_T: int
    CURSOR_DIRECTION_B: int
    CURSOR_DIRECTION_LT: int
    CURSOR_DIRECTION_RT: int
    CURSOR_DIRECTION_LB: int
    CURSOR_DIRECTION_RB: int

class AdjustingContainer(Container): ...
class AnimationIcon(Widget): ...
class BarGraph(Widget): ...
class Button(Widget): ...
class CheckBox(Widget): ...
class CurveGraph(Widget): ...
class DockArea(Container): ...
class DropDown(Widget): ...
class FlowContainer(Container): ...
class Icon(Widget): ...
class IconProgressBar(Widget): ...
class ImageButton(Button): ...
class ImageProgressBar(Widget): ...
class Label(Widget): ...
class LineGraph(Widget): ...
class ListBox(Widget): ...
class Panel(Container): ...
class PasswordField(Widget): ...
class PieGraph(Widget): ...
class PointGraph(Widget): ...
class RadioButton(Widget): ...
class Spacer(Widget): ...
class Tab(Widget): ...
class TabbedArea(Container): ...
class TextBox(Widget): ...
class TextField(Widget): ...
class ToggleButton(Button): ...
class Window(Container): ...

def __getattr__(name: str) -> Any: ...
