import os
from utils.util_scripts.path import path

Import('env')

curpath = str(path('.'))
installpath = str((path('.') / path('install')).abspath())

os.chdir( str( path( '.' ) / path( 'minizip' ) ) )
os.system( 'make' )
os.system( 'make install prefix=%s' % installpath )
for f in path('.').files('*.h'): f.copy(path('..') / path('install') / path('include'))
os.chdir( '..' )

os.chdir(str(path('.') / path('guichan-0.6.1')))

os.system('./configure')
os.system('make')
os.system('make install prefix=%s' % installpath)

os.chdir(curpath)

