import os
from utils.util_scripts.path import path

Import('env')

curpath = str(path('.'))
installpath = str((path('.') / path('install')).abspath())

os.chdir(str(path('.') / path('guichan-0.7.1')))

os.system('./configure')
os.system('make')
os.system('make install prefix=%s' % installpath)

os.chdir(str(path('..')))

os.chdir(str(path('.') / path('libpng-1.2.29')))

os.system('./configure')
os.system('make all-am')
os.system('make install prefix=%s' % installpath)
os.system('make install-data-hook prefix=%s' % installpath)

os.chdir('..')
os.chdir(str(path('.') / path('openal-soft')))
os.system('./configure')
os.system('make')
os.system('make install prefix=%s' % installpath)

os.chdir(curpath)
