import glob

Import('env')

env = env.Copy()
env.Append(CPPPATH = ['#src/engine'])
env.Append(LIBS = ['fife','boost_unit_test_framework'])
env.Append(LIBPATH = ['#src/engine'])

# geometry test removed, API has been changed but test are not up-to-date
# env.Program('test_geometry', ['test_geometry.cpp'])

# The test_all.py script relies on this specific layout.
# Check it, if you change something here
env.Program('test_settingsmanager', ['test_settingsmanager.cpp'])
env.Program('test_rect', ['test_rect.cpp'])
env.Program('test_events', ['test_events.cpp'])
env.Program('test_objects', ['test_objects.cpp'])

# vim: set filetype=python :
