import glob

Import('env_sdl')

env = env_sdl.Copy()
env.Append(CPPPATH = ['#src/engine','#src/guichan_addon'])
env.Append(LIBS = ['fife', 'guichanfife'])
env.Append(LIBPATH = ['#src/engine','#src/guichan_addon'])

files = glob.glob('*.cpp')
env.Program('testproj', files)

# vim: set filetype=python :
