import os
import glob

Import('env')

# We have to avoid using vfswriteformat if we're building the lite version.
# At least, according to the old scripts.
files = [os.path.join('vfs', x) for x in glob.glob('*.cpp') 
         if not (x.endswith('vfswriteformat.cpp') and env['lite'])]

Return('files')
