Import('env')

if env['lite'] == 0:
	SConscript([
				'engine/SConscript',
        	    'testproject/SConscript',
            	'menutest/SConscript',
	            'guitest/SConscript'
				])

if env['lite'] == 1:
	SConscript([
				'engine/SConscript'
				])

# vim: set filetype=python :
