import glob

Import('env')

env = env.Copy()
env.Append(CPPPATH = ['../../core/src/engine'])
env.Append(LIBPATH = ['../../core/src/engine'])

files = glob.glob('*.cpp')
env.Program('frminfo', files)

# vim: set filetype=python :
