corepath = '../../exp_core'

bld = Builder(action = 'sh build_doc.sh $SOURCE $TARGET')
env1 = Environment(BUILDERS = {'Cpp': bld})

env1.Cpp('usage_tilemaker.cpp', 'imgtool_usage.txt')
env1.Cpp('usage_luaimage.cpp', 'luaimage_usage.txt')

env = Environment()
env.Append(CPPPATH = ['/usr/include/SDL'])

env.Program('tilemaker', ['imgtool.cpp', 'usage_tilemaker.cpp'],
  LIBS=['SDL', 'SDL_image', 'png'])
  
env.Append(CPPPATH = ['/usr/include/lua50'])
env.Program('luaimage', ['luaimage.cpp', 'usage_luaimage.cpp', 'write_png.cpp'],
  LIBS=['SDL', 'SDL_image', 'lua50', 'lualib50'])
# vim: set filetype=python:
