#!/usr/bin/env python3
"""generate_enum.py — Generate a C++ header mirroring SDL3 keycodes.

Reads JSON from stdin (produced by parse_sdl3.py) and writes a C++ header
to stdout.  The generated file contains:
  - A `FIFE_SDL_KEYMAP_VERSION` macro (the SDL3 version it was built from).
  - An anonymous enum inside `FIFE::Key` matching all `SDLK_*` constants.
  - Inline helpers: `get_name()`, `is_printable()`.

Usage:
    parse_sdl3.py /path/to/SDL_keycode.h | python3 generate_enum.py > key_gen.h
"""

import json
import sys

HEADER = """\
// SPDX-License-Identifier: LGPL-2.1-or-later
// SPDX-FileCopyrightText: 2005 - 2026 Fifengine contributors
//
// ---------------------------------------------------------------------------
// Warning, this file is autogenerated. Do not edit directly.
// ---------------------------------------------------------------------------
// Generated from SDL_keycode.h of SDL3 v{version}
// ---------------------------------------------------------------------------
// To re-generate:
//   1. cmake --build . --target sync_keys_with_SDL3
//   or delete this file and rebuild.
// ---------------------------------------------------------------------------

#ifndef FIFE_KEY_GEN_H
#define FIFE_KEY_GEN_H

#include <cstdint>

/** SDL3 version used to generate this key map. */
#define FIFE_SDL_KEYMAP_VERSION {version_num}u

namespace FIFE {{

/** Mirrors SDL3's SDLK_* constants, isolated in a dedicated sub-namespace
 *  to avoid polluting the FIFE root namespace or conflicting with class
 *  member enums.  Consumers can bring individual keys into scope with
 *  `using FIFE::Keys::RETURN;` or use them fully qualified as `FIFE::Keys::RETURN`.
 *  The FIFE::Key class typedefs `KeyType` and provides backward-compat aliases.
 */
namespace Keys {{

enum KeyType : uint32_t {{
{body}
}};

}} // namespace Keys

static_assert(sizeof(Keys::KeyType) == sizeof(uint32_t),
              "KeyType must be 32-bit to match SDL_Keycode");

}} // namespace FIFE

#endif // FIFE_KEY_GEN_H
"""


# Names that would conflict with other symbols in the FIFE namespace.
CONFLICT_RENAME = {
    'LESS':    'KEY_LESS',
    'GREATER': 'KEY_GREATER',
    'UNKNOWN': 'KEY_UNKNOWN',
}


def to_enum_name(name: str) -> str:
    """Convert SDLK_FOO to FOO, prefix numeric-leading names with _."""
    s = name.removeprefix('SDLK_')
    if s and s[0].isdigit():
        s = '_' + s
    # Rename conflicting names
    if s in CONFLICT_RENAME:
        return CONFLICT_RENAME[s]
    return s


def generate(data: dict) -> str:
    v = data['version']
    maj, min_, mic = v
    version_num = maj * 1_000_000 + min_ * 1_000 + mic

    lines = []
    for k in data['keys']:
        name = k['name']
        value = k['value']
        comment = k['comment']
        enum_entry = to_enum_name(name)
        if comment:
            lines.append(f'    {enum_entry:45s} = {value}u, // {comment}')
        else:
            lines.append(f'    {enum_entry:45s} = {value}u,')

    body = '\n'.join(lines)

    return HEADER.format(
        version=f'{maj}.{min_}.{mic}',
        maj=maj, min=min_, mic=mic,
        version_num=version_num,
        body=body,
    )


if __name__ == '__main__':
    data = json.load(sys.stdin)
    print(generate(data), end='')
