#!/usr/bin/env python3
"""generate_enum.py — Generate a C++ header mirroring SDL3 keycodes.

Reads JSON from stdin (produced by parse_sdl3.py) and writes a C++ header
to stdout.  The generated file contains:
  - A `FIFE_SDL_KEYMAP_VERSION` macro (the SDL3 version it was built from).
  - An anonymous enum inside `FIFE::Key` matching all `SDLK_*` constants.
  - Inline helpers: `get_name()`, `is_printable()`.

Usage:
    parse_sdl3.py /path/to/SDL_keycode.h | python3 generate_enum.py > key_gen.h
"""

import json
import sys

HEADER = """\
// SPDX-License-Identifier: LGPL-2.1-or-later OR BSD-3-Clause
// SPDX-FileCopyrightText: 2005 - 2026 Fifengine contributors

// ---------------------------------------------------------------------------
// This file is autogenerated from SDL_keycode.h of SDL3 v{version}.
// Do not edit.
// ---------------------------------------------------------------------------

#ifndef FIFE_KEY_GEN_H
#define FIFE_KEY_GEN_H

#include <cstdint>

// SDL3 version used to generate this key map.
#define FIFE_SDL_KEYMAP_VERSION {version_num}u

namespace FIFE
{{

    /**
     * Mirrors SDL3 `SDLK_*` constants as `uint32_t`.
     *
     * Keycodes are semantic and represent the intended character or symbol.
     * `SDLK_a` refers to the logical "A" key regardless of keyboard layout.
     *
     * Scancodes are physical and identify a fixed key position.
     * `SDL_SCANCODE_A` always refers to the same physical key.
     * The OS maps scancodes to keycodes using the active keyboard layout.
     */
    namespace Keys
    {{

        enum KeyType : uint32_t
        {{
{body}
        }};

    }} // namespace Keys

    static_assert(sizeof(Keys::KeyType) == sizeof(uint32_t), "KeyType must be 32-bit to match SDL_Keycode");

}} // namespace FIFE

#endif // FIFE_KEY_GEN_H
"""


# Names that would conflict with other symbols in the FIFE namespace.
CONFLICT_RENAME = {
    "LESS": "KEY_LESS",
    "GREATER": "KEY_GREATER",
    "UNKNOWN": "KEY_UNKNOWN",
    "DELETE": "KEY_DELETE",  # <winnt.h>
    "OUT": "KEY_OUT",  # <windef.h>
    "IN": "KEY_IN",  # <windef.h>
    "NEAR": "KEY_NEAR",  # <windef.h>
    "FAR": "KEY_FAR",  # <windef.h>
    "CANCEL": "KEY_CANCEL",  # <winuser.h>
    "CLEAR": "KEY_CLEAR",  # <winuser.h>
    "COPY": "KEY_COPY",  # <winuser.h>
    "SELECT": "KEY_SELECT",  # <winuser.h>
}


def to_enum_name(name: str) -> str:
    """Convert SDLK_FOO to FOO, prefix numeric-leading names with _."""
    s = name.removeprefix("SDLK_")
    if s and s[0].isdigit():
        s = "_" + s
    # Rename conflicting names
    if s in CONFLICT_RENAME:
        return CONFLICT_RENAME[s]
    return s


def generate(data: dict) -> str:
    v = data["version"]
    maj, min_, mic = v
    version_num = maj * 1_000_000 + min_ * 1_000 + mic

    lines = []
    for k in data["keys"]:
        name = k["name"]
        value = k["value"]
        comment = k["comment"]
        enum_entry = to_enum_name(name)
        if comment:
            lines.append(f"            {enum_entry:20s} = {value}u, // {comment}")
        else:
            lines.append(f"            {enum_entry:20s} = {value}u,")

    body = "\n".join(lines)

    return HEADER.format(
        version=f"{maj}.{min_}.{mic}",
        maj=maj,
        min=min_,
        mic=mic,
        version_num=version_num,
        body=body,
    )


if __name__ == "__main__":
    data = json.load(sys.stdin)
    print(generate(data), end="")
