Import('env')

FILESLIST = [ 'glimage.cpp', 'renderbackendopengl.cpp', 'glscreen.cpp' ]

objlist = []

for file in FILESLIST:
	objlist += env.Object(file)

Return('objlist')

# vim: set filetype=python :
