name: Build FIFEngine

on:
  push:
    #branches: [ master, main, resurge ]
  pull_request:
    #branches: [ master, main ]
  workflow_dispatch:

# Improve CI concurrency by automatically cancelling outdated jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build on ${{ matrix.os }}"

    # https://github.com/actions/runner-images#available-environments
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
        # Clang 16
          - os: ubuntu-24.04
            preset: clang16-x64-linux-rel-ci
            triplet: x64-linux
            artifact-name: libfife-linux-x64
        # GCC 14
          - os: ubuntu-24.04
            preset: gcc14-x64-linux-rel-ci
            triplet: x64-linux
            artifact-name: libfife-linux-x64
        # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
          - os: windows-2025
            preset: vc17-x64-windows-rel
            triplet: x64-windows
            artifact-name: libfife-windows-x64

    steps:
      - name: 🤘 Checkout Code
        uses: actions/checkout@v6 # https://github.com/actions/checkout

      - name: 🔽 Set up Python (for vcpkg.sh)
        if: matrix.os == 'ubuntu-24.04'
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 🔽 Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt update -qq
          sudo apt install -y libglu1-mesa-dev autoconf libtool python3-jinja2 autoconf-archive automake libxmu-dev libxi-dev libgl-dev
          echo -e "libxcrypt depends on ltdl development files from the system package manager:"
          sudo apt install -y libltdl-dev

      # WARNING
      # ENV VCPKG_ROOT is redefined by this action
      # and set to "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\vcpkg"
      # instead of "c:\vcpkg", which is important for the pre-installed VCPKG on GHA.
      - name: 🛠️ Setup Visual Studio Developer Command Prompt
        if: matrix.os == 'windows-2025'
        uses: ilammy/msvc-dev-cmd@v1

      # Default Location is "c:\vcpkg"
      - name: 🔽 Define VCPKG_ROOT
        if: matrix.os == 'windows-2025'
        shell: pwsh
        run: |
          $VCPKG_ROOT=$($env:VCPKG_INSTALLATION_ROOT)
          echo "VCPKG_ROOT=$($VCPKG_ROOT)" >> $env:GITHUB_ENV

      - name: 🔽 Install dependencies via vcpkg
        run: vcpkg install --triplet ${{ matrix.triplet }}

      - name: 🛠️ CMake ➔ Configure
        run: |
          cmake --preset ${{ matrix.preset }} -Dfifechan=OFF -Dbuild-python=OFF -Dbuild-library=ON

      - name: 🙏 CMake ➔ Build
        run: cmake --build out/build/${{ matrix.preset }}

      - name: 📦 CMake ➔ Install
        run: cmake --install out/build/${{ matrix.preset }}

      - name: ❔Verify build output
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-24.04" ]; then
            ls -la out/install/${{ matrix.preset }}/lib/libfife.so*
          else
            dir out\install\${{ matrix.preset }}\lib\libfife.*
          fi
        shell: bash

      - name: 🔼 Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: out/install/${{ matrix.preset }}/**
          retention-days: 30
