name: Build FIFEngine

on:
  push:
    #branches: [ master, main, resurge ]
  pull_request:
    #branches: [ master, main ]
  workflow_dispatch:

# Improve CI concurrency by automatically cancelling outdated jobs
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "${{ matrix.name }}"

    # https://github.com/actions/runner-images#available-environments
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
        # https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
        # Clang 16
          - name: "Linux, Clang 16, Release"
            os: ubuntu-24.04
            preset: clang16-x64-linux-rel-ci
            triplet: x64-linux
            artifact-name: libfife-linux-x64
        # GCC 14
          - name: "Linux, GCC 14, Release"
            os: ubuntu-24.04
            preset: gcc14-x64-linux-rel-ci
            triplet: x64-linux
            artifact-name: libfife-linux-x64
        # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
          - name: "Win, VC17, Release"
            os: windows-2025
            preset: vc17-x64-windows-rel-ci
            triplet: x64-windows
            artifact-name: libfife-windows-x64

    steps:
      - name: 🤘 Checkout Code
        uses: actions/checkout@v6 # https://github.com/actions/checkout

      - name: 🔽 Set up Python (for vcpkg.sh)
        if: matrix.os == 'ubuntu-24.04'
        uses: actions/setup-python@v6 # https://github.com/actions/setup-python
        with:
          python-version: '3.x'

      - name: 🔽 Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt update -qq
          sudo apt install -y libglu1-mesa-dev autoconf libtool python3-jinja2 autoconf-archive automake libxmu-dev libxi-dev libgl-dev
          echo -e "libxcrypt depends on ltdl development files from the system package manager:"
          sudo apt install -y libltdl-dev

      # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md#visual-studio-enterprise-2022
      - name: Setup MSVC Dev Environment
        if: matrix.os == 'windows-2025'
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"

      # Default Locations (env var VCPKG_INSTALLATION_ROOT):
      # Windows: "c:\vcpkg"
      # Linux: /usr/local/share/vcpkg
      - name: 🔽 Update VCPKG
        run: |
          cd "${{ env.VCPKG_INSTALLATION_ROOT }}"
          git reset --hard
          git pull --quiet

      - name: 🔽 Integrate VCPKG
        run: |
          bootstrap-vcpkg.bat
          vcpkg integrate

      - name: 🛠️ CMake ➔ Configure
        run: |
          cmake --preset ${{ matrix.preset }} -Dfifechan=OFF -Dbuild-python=OFF -Dbuild-library=ON

      - name: 🙏 CMake ➔ Build
        run: cmake --build out/build/${{ matrix.preset }}

      - name: 📦 CMake ➔ Install
        run: cmake --install out/build/${{ matrix.preset }}

      - name: ❔ CHECK important folders, to see if everything is present (after building)
        run: |
          ls out/build/${{ matrix.config.preset }}
          ls out/install/${{ matrix.config.preset }}

      - name: 🔼 Upload build artifacts
        uses: actions/upload-artifact@v6 # https://github.com/actions/upload-artifact
        with:
          name: ${{ matrix.artifact-name }}
          path: out/install/${{ matrix.preset }}/**
          retention-days: 30
